name: Codespaces Prebuilds

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # Rebuild prebuilds weekly on Sunday at 2 AM UTC
    - cron: "0 2 * * 0"
  workflow_dispatch:

jobs:
  prebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      codespaces: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create Codespace prebuild
      uses: github/codespaces-prebuild-action@v1
      with:
        devcontainer_path: '.devcontainer/devcontainer.json'
        machine: 'basicLinux32gb'
        ref: ${{ github.ref }}
        
    - name: Verify prebuild creation
      run: |
        echo "✅ Codespace prebuild created successfully"
        echo "🚀 This will speed up Codespace creation for ChipFlow development"